language: ruby
rvm:
  - 2.1


before_install:
  - gem update --system
  - gem --version


script:
  - bundle exec jekyll build
  - bundle exec htmlproof ./_site --only-4xx --check-favicon --check-html


env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
