# R - Hyper Minimal Jekyll Theme
# Copyright 2015 Rahul Thakur (r@rahulthakur.me)


# Setup
isLive:                 true # true = live :: false = dev
version:                1.0.0
title:                  Rahul Thakur
description:            Personal website of Rahul Thakur
url:                    http://rahulthakur.me
ip:                     192.168.2.6 # for local dev with live-reload
locale:                 en_IN
timezone:               Asia/Hong_Kong
logo:                   /assets/img/logo.png
disqus_comments:        rahulrkt # leave blank to disable


# Author Details
author:
  avatar:               /assets/img/me-light.png
  name:                 Rahul Thakur
  tagline:              MusicBuff - Gamer - Coder
  blurb:                I Love DC Comics, MCR, Megadeth, Chocolates, Eggs. I Drink Beer, Whiskey, Black Coffee. I Enjoy Lazy-ing, Eating, Daydreaming.

  # Social Links [ key=font-awesome :: value=href ]
  social:
    globe:              http://rahulthakur.me
    envelope-o:         mailto:r@rahulthakur.me
    twitter:            http://twitter.com/_rahulthakur
    linkedin:           http://www.linkedin.com/in/rahulkthakur
    github-alt:         http://github.com/rahul-rkt
    bitbucket:          http://bitbucket.org/_rahulthakur
    stack-overflow:     http://stackoverflow.com/users/1127443

  cv:                   /assets/pdf/CV.pages.pdf
  keywords:             [ rahul thakur, rahulthakur, rahul, thakur, rkt, dd, catastrophe corporation, catastrophe corp, catcorp, cc, developer, programmer, coder, designer, java, android, php, jekyll, sass, musicbuff, gamer ]


# Navigation
nav:
  work:                 /work
  archive:              /archive
  about:                /about


# SEO
seo:
  twitter:              _rahulthakur
  google_plus:          +RahulThakurRKT
  google_analytics:     UA-62417983-3
  google_verification:  lH_YbKTfJUHwERczHyXd2AKj_2LlFwiZx6bUCqsrSd8
  bing_verification:    03805AEA078E6A84C402D95910C0D212


# Post Directives
future:                 true
permalink:              /:categories/:title/
relative_permalinks:    true
paginate:               1


# Dependencies
markdown:               kramdown
highlighter:            pygments

kramdown:
  input:                GFM
  auto_ids:             true
  footnote_nr:          1
  entity_output:        as_char
  toc_levels:           1..6
  smart_quotes:         [ "apos", "apos", "quot", "quot" ]
  parse_block_html:     true
  hard_wrap:            false
  enable_coderay:       true
  coderay_line_numbers:           nil
  coderay_line_numbers_start:     1
  coderay_tab_width:              4
  coderay_bold_every:             5
  extensions:
    - autolink
    - footnotes
    - smart


# Build Directives
safe:                   true
lsi:                    false
excerpt_separator:      ""
gems:
  - jekyll-sitemap
  - bourbon
  - neat

exclude:                [ "tmp", "vendor", "toolbelt", "public", "config.ru", "Gemfile", "Gemfile.lock", "Guardfile", ".travis.yml" ]
